server:
  port: 9001 # UserService port

spring:
  application:
    name: UserService

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: pgAdmin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Optional: logging SQL parameters (for debugging)
  # jpa:
  #   properties:
  #     hibernate:
  #       format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Discovery Server

    fetch-registry: true
    register-with-eureka: true
